const UPDATE_USER = 'UPDATE_USER';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const SET_PROVINCE = 'SET_PROVINCE';
const SET_REGENCY = 'SET_REGENCY';
const SET_DISTRICT = 'SET_DISTRICT';
const SET_SUBDISTRICT = 'SET_SUBDISTRICT';
const SET_USER = 'SET_USER';
const SET_DEVICE = 'SET_DEVICE';
const SET_DETAIL_CUSTOMER = 'SET_DETAIL_CUSTOMER';
const SET_ACTIVITY_HISTORY = 'SET_ACTIVITY_HISTORY';
const SET_PAYMENT_HISTORY = 'SET_PAYMENT_HISTORY';
const SET_PIN = 'SET_PIN';
const SET_CONTACT_MODE = 'SET_CONTACT_MODE';
const SET_CONTACT_PERSON = 'SET_CONTACT_PERSON';
const SET_PLACE_CONTACTED = 'SET_PLACE_CONTACTED';
const SET_CALL_RESULT = 'SET_CALL_RESULT';
const SET_GEOLOCATION = 'SET_GEOLOCATION';
const SET_REFRESH_COORDINATE = 'SET_REFRESH_COORDINATE';
const SET_IDLE_TIME = 'SET_IDLE_TIME';
const SET_BEDA_JAM = 'SET_BEDA_JAM';
const SET_MAX_BEDA_JAM = 'SET_MAX_BEDA_JAM';

export {
    UPDATE_USER,
    INCREMENT,
    DECREMENT,
    SET_PROVINCE,
    SET_REGENCY,
    SET_DISTRICT,
    SET_SUBDISTRICT,
    SET_USER,
    SET_DEVICE,
    SET_DETAIL_CUSTOMER,
    SET_ACTIVITY_HISTORY,
    SET_PAYMENT_HISTORY,
    SET_PIN,
    SET_CONTACT_MODE,
    SET_CONTACT_PERSON,
    SET_PLACE_CONTACTED,
    SET_CALL_RESULT,
    SET_GEOLOCATION,
    SET_REFRESH_COORDINATE,
    SET_IDLE_TIME,
    SET_BEDA_JAM,
    SET_MAX_BEDA_JAM,
}