const UPDATE_USER = 'UPDATE_USER';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const SET_PROVINCE = 'SET_PROVINCE';
const SET_REGENCY = 'SET_REGENCY';
const SET_DISTRICT = 'SET_DISTRICT';
const SET_SUBDISTRICT = 'SET_SUBDISTRICT';
const SET_USER = 'SET_USER';
const SET_DEVICE = 'SET_DEVICE';
const SET_DETAIL_CUSTOMER = 'SET_DETAIL_CUSTOMER';
const SET_ACTIVITY_HISTORY = 'SET_ACTIVITY_HISTORY';
const SET_PAYMENT_HISTORY = 'SET_PAYMENT_HISTORY';

export {
    UPDATE_USER,
    INCREMENT,
    DECREMENT,
    SET_PROVINCE,
    SET_REGENCY,
    SET_DISTRICT,
    SET_SUBDISTRICT,
    SET_USER,
    SET_DEVICE,
    SET_DETAIL_CUSTOMER,
    SET_ACTIVITY_HISTORY,
    SET_PAYMENT_HISTORY,
}