const PIN = "PIN";
const LIST_ACCOUNT = "LIST_ACCOUNT";
const DETAIL_COSTUMER = "DETAIL_COSTUMER";
const ACTIVITY_HISTORY = "ACTIVITY_HISTORY";
const PAYMENT_HISTORY = "PAYMENT_HISTORY";
const DEVICE_INFO = "DEVICE_INFO";

export {
    PIN,
    LIST_ACCOUNT,
    DETAIL_COSTUMER,
    ACTIVITY_HISTORY,
    PAYMENT_HISTORY,
    DEVICE_INFO,
}