const PIN = "PIN";
const LIST_ACCOUNT = "LIST_ACCOUNT";
const DETAIL_COSTUMER = "DETAIL_COSTUMER";
const ACTIVITY_HISTORY = "ACTIVITY_HISTORY";
const PAYMENT_HISTORY = "PAYMENT_HISTORY";
const DEVICE_INFO = "DEVICE_INFO";
const REFERENCE = "REFERENCE";
const RENCANA_KUNJUNGAN = "RENCANA_KUNJUNGAN";
const REKAP_TERKIRIM = "REKAP_TERKIRIM";
const REKAP_TERTUNDA = "REKAP_TERTUNDA";
const GEOLOCATION = "GEOLOCATION";
const DAFTAR_DIKUNJUNGI = "DAFTAR_DIKUNJUNGI";

export {
    PIN,
    LIST_ACCOUNT,
    DETAIL_COSTUMER,
    ACTIVITY_HISTORY,
    PAYMENT_HISTORY,
    DEVICE_INFO,
    REFERENCE,
    RENCANA_KUNJUNGAN,
    REKAP_TERKIRIM,
    REKAP_TERTUNDA,
    GEOLOCATION,
    DAFTAR_DIKUNJUNGI,
}