import LocalizedStrings from 'react-localization';

let AddKunjungan = new LocalizedStrings({
    "ID": {
        title: 'INPUT HASIL KUNJUNGAN',
        optionPlacholder: 'PILIH',
        kunjunganTitle: 'Hasil Kunjungan',
        tanggalPTPLabel: 'Tanggal PTP',
        ptpAmountLabel: 'PTP Amount',
        paymentLabel : 'Payment Option',
        hasilKunjunganLabel : 'Detail Hasil Kunjungan (Remarks)',
        fotoLabel : 'Foto Dokumendasi',
        provLabel : 'Visit Provinsi',
        kabLabel : 'Visit Kabupaten',
        kecLabel : 'Visit Kecamatan',
        kelLabel : 'Visit Kelurahan',
        addLabel : 'Address',
        phone1TypeLabel : 'New Phone Number 1 Type',
        phone1Label : 'New Phone Number 1',
        phone2TypeLabel : 'New Phone Number 2 Type',
        phone2Label : 'New Phone Number 2',
        metodeKontakLabel : 'Metode Kontak',
        detailMetodeKontakLabel : 'Detail Metode Kontak',
        tempatKunjunganLabel : 'Tempat Kunjungan',
        lokasiLabel : 'Lokasi',
        kirim : 'KIRIM',
        batal : 'BATAL',
    },
    "EN": {
        title: 'INPUT VISIT RESULT',
        optionPlacholder: 'Choose',
        kunjunganTitle: 'Visit Result',
        tanggalPTPLabel: 'PTP Date',
        ptpAmountLabel: 'PTP Amount',
        paymentLabel : 'Payment Option',
        hasilKunjunganLabel : 'Visit Result Detail (Remarks)',
        fotoLabel : 'Documentation Picture',
        provLabel : 'Visit Province',
        kabLabel : 'Visit Regenecy',
        kecLabel : 'Visit District',
        kelLabel : 'Visit Sub-District',
        addLabel : 'Address',
        phone1TypeLabel : 'New Phone Number 1 Type',
        phone1Label : 'New Phone Number 1',
        phone2TypeLabel : 'New Phone Number 2 Type',
        phone2Label : 'New Phone Number 2',
        metodeKontakLabel : 'Contact Method',
        detailMetodeKontakLabel : 'Contact Method Detail',
        tempatKunjunganLabel : 'Visit Place',
        lokasiLabel : 'Location',
        kirim : 'SEND',
        batal : 'CANCEL',
    },
});

export default AddKunjungan;